apiVersion: v1
kind: Service
metadata:
  labels:
    app: conntrackd
  name: conntrackd
  namespace: monitoring
spec:
  clusterIP: None
  ports:
  - name: metrics
    port: 2112
    targetPort: 2112
  selector:
    app: conntrackd
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: conntrackd
  name: conntrackd
  namespace: monitoring
spec:
  endpoints:
  - interval: 30s
    port: metrics
  namespaceSelector:
    matchNames:
    - monitoring
  selector:
    matchLabels:
      app: conntrackd